version: "3.9"
volumes:
  db-store:
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - target: 3000
        published: ${WEB_PORT:-3000}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: .
        target: /myapp
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME:-rails_db}
      - MYSQL_USER=${DB_USER:-rails_user}
      - MYSQL_PASSWORD=${DB_PASS:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-password}
